import { Product, Sale, MonthlyBalance, Client } from "./types";

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Mate Imperial Calabaza",
    subtitle: "Cuero repujado con virola de alpaca",
    sku: "MT-0142",
    category: "Mates",
    listPrice: 12500,
    price: 18900,
    stock: 42,
    status: "En stock",
  },
  {
    id: "prod-2",
    name: "Mate Torpedo Premium",
    subtitle: "Cuero vaqueta seleccionado marrón",
    sku: "MT-0143",
    category: "Mates",
    listPrice: 11000,
    price: 16500,
    stock: 8,
    status: "Bajo stock",
  },
  {
    id: "prod-3",
    name: "Mate Camionero Uruguayo",
    subtitle: "Boca ancha, virola cincelada lisa",
    sku: "MT-0144",
    category: "Mates",
    listPrice: 13000,
    price: 19800,
    stock: 24,
    status: "En stock",
  },
  {
    id: "prod-4",
    name: "Bombilla Pico de Loro Alpaca",
    subtitle: "Filtro cuchara resorte desmontable",
    sku: "BB-0201",
    category: "Bombillas",
    listPrice: 4800,
    price: 7200,
    stock: 65,
    status: "En stock",
  },
  {
    id: "prod-5",
    name: "Bombilla Cincelada Especial",
    subtitle: "Alpaca con detalles artesanales",
    sku: "BB-0205",
    category: "Bombillas",
    listPrice: 5800,
    price: 8900,
    stock: 4,
    status: "Bajo stock",
  },
  {
    id: "prod-6",
    name: "Set Mate Imperial + Kit",
    subtitle: "Incluye mate, bombilla y bolso matero",
    sku: "ST-0501",
    category: "Sets",
    listPrice: 23000,
    price: 34500,
    stock: 15,
    status: "En stock",
  },
  {
    id: "prod-7",
    name: "Yerba Mate Artesanal Barbaquá 1kg",
    subtitle: "Estacionamiento natural 24 meses",
    sku: "YB-0010",
    category: "Yerba",
    listPrice: 3000,
    price: 4500,
    stock: 120,
    status: "En stock",
  },
  {
    id: "prod-8",
    name: "Termo Acero Inoxidable 1L",
    subtitle: "Doble capa térmica con manija cuero",
    sku: "TM-0301",
    category: "Termos",
    listPrice: 19000,
    price: 28900,
    stock: 0,
    status: "Agotado",
  },
  {
    id: "prod-9",
    name: "Canasta Matera Cuero Genuino",
    subtitle: "Divisiones acolchadas reforzadas",
    sku: "AC-0402",
    category: "Accesorios",
    listPrice: 15000,
    price: 22400,
    stock: 6,
    status: "Bajo stock",
  },
];

export const initialClients: Client[] = [
  {
    id: "cli-1",
    name: "Lucía Fernández",
    initials: "LF",
    phone: "+54 9 11 4500-1000",
    email: "lucia.fernandez@gmail.com",
    dni: "38.291.482",
  },
  {
    id: "cli-2",
    name: "Mateo Gómez",
    initials: "MG",
    phone: "+54 9 11 4537-1082",
    email: "mateo.gomez@gmail.com",
    dni: "41.982.113",
  },
  {
    id: "cli-3",
    name: "Diego Torres",
    initials: "DT",
    phone: "+54 9 11 4574-1164",
    email: "diego.torres@gmail.com",
    dni: "35.109.842",
  },
  {
    id: "cli-4",
    name: "Camila Rodríguez",
    initials: "CR",
    phone: "+54 9 11 4611-1246",
    email: "camila.rodriguez@gmail.com",
    dni: "42.741.005",
  },
  {
    id: "cli-5",
    name: "Juan Pablo Rossi",
    initials: "JR",
    phone: "+54 9 11 4648-1328",
    email: "juan.rossi@gmail.com",
    dni: "33.820.491",
  },
];

export const initialSales: Sale[] = [
  // ── Lucía Fernández: todo al día ─────────────────────────────────────────
  {
    id: "sale-1",
    clientId: "cli-1",
    clientName: "Lucía Fernández",
    clientInitials: "LF",
    clientPhone: "+54 9 11 4500-1000",
    clientEmail: "lucia.fernandez@gmail.com",
    clientDni: "38.291.482",
    productName: "Set Mate Imperial + Kit",
    date: "19 Sep",
    method: "Efectivo",
    amount: 34500,
    paidAmount: 34500,
    status: "Completada",
  },
  {
    id: "sale-6",
    clientId: "cli-1",
    clientName: "Lucía Fernández",
    clientInitials: "LF",
    clientPhone: "+54 9 11 4500-1000",
    clientEmail: "lucia.fernandez@gmail.com",
    clientDni: "38.291.482",
    productName: "Bombilla Cincelada Especial",
    date: "10 Sep",
    method: "Transferencia",
    amount: 8900,
    paidAmount: 8900,
    status: "Completada",
  },

  // ── Mateo Gómez: DEUDA TOTAL — nunca pagó ────────────────────────────────
  {
    id: "sale-2",
    clientId: "cli-2",
    clientName: "Mateo Gómez",
    clientInitials: "MG",
    clientPhone: "+54 9 11 4537-1082",
    clientEmail: "mateo.gomez@gmail.com",
    clientDni: "41.982.113",
    productName: "Mate Imperial Calabaza",
    date: "19 Sep",
    method: "Fiado",
    amount: 18900,
    paidAmount: 0,
    status: "Pendiente",
  },
  {
    id: "sale-7",
    clientId: "cli-2",
    clientName: "Mateo Gómez",
    clientInitials: "MG",
    clientPhone: "+54 9 11 4537-1082",
    clientEmail: "mateo.gomez@gmail.com",
    clientDni: "41.982.113",
    productName: "Yerba Barbaquá 1kg x2",
    date: "15 Sep",
    method: "Fiado",
    amount: 9000,
    paidAmount: 0,
    status: "Pendiente",
  },

  // ── Diego Torres: al día ──────────────────────────────────────────────────
  {
    id: "sale-3",
    clientId: "cli-3",
    clientName: "Diego Torres",
    clientInitials: "DT",
    clientPhone: "+54 9 11 4574-1164",
    clientEmail: "diego.torres@gmail.com",
    clientDni: "35.109.842",
    productName: "Mate Torpedo + Kit",
    date: "18 Sep",
    method: "Transferencia",
    amount: 22300,
    paidAmount: 22300,
    status: "Completada",
  },

  // ── Camila Rodríguez: DEUDA PARCIAL — pagó $10.000, debe $38.700 ─────────
  {
    id: "sale-4",
    clientId: "cli-4",
    clientName: "Camila Rodríguez",
    clientInitials: "CR",
    clientPhone: "+54 9 11 4611-1246",
    clientEmail: "camila.rodriguez@gmail.com",
    clientDni: "42.741.005",
    productName: "Termo Acero 1L + Mate Camionero",
    date: "18 Sep",
    method: "Efectivo parcial",
    amount: 48700,
    paidAmount: 10000,
    status: "Pendiente",
  },
  {
    id: "sale-8",
    clientId: "cli-4",
    clientName: "Camila Rodríguez",
    clientInitials: "CR",
    clientPhone: "+54 9 11 4611-1246",
    clientEmail: "camila.rodriguez@gmail.com",
    clientDni: "42.741.005",
    productName: "Bombilla Pico de Loro Alpaca",
    date: "5 Sep",
    method: "Mercado Pago",
    amount: 7200,
    paidAmount: 7200,
    status: "Completada",
  },

  // ── Juan Pablo Rossi: MÚLTIPLES DEUDAS ($35.900 pendientes) ──────────────
  {
    id: "sale-5",
    clientId: "cli-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    clientPhone: "+54 9 11 4648-1328",
    clientEmail: "juan.rossi@gmail.com",
    clientDni: "33.820.491",
    productName: "Canasta Matera Cuero Genuino",
    date: "17 Sep",
    method: "Fiado",
    amount: 22400,
    paidAmount: 0,
    status: "Pendiente",
  },
  {
    id: "sale-9",
    clientId: "cli-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    clientPhone: "+54 9 11 4648-1328",
    clientEmail: "juan.rossi@gmail.com",
    clientDni: "33.820.491",
    productName: "Yerba Barbaquá 1kg x3",
    date: "10 Sep",
    method: "Fiado",
    amount: 13500,
    paidAmount: 0,
    status: "Pendiente",
  },
  {
    id: "sale-10",
    clientId: "cli-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    clientPhone: "+54 9 11 4648-1328",
    clientEmail: "juan.rossi@gmail.com",
    clientDni: "33.820.491",
    productName: "Mate Imperial Calabaza",
    date: "2 Sep",
    method: "Transferencia",
    amount: 18900,
    paidAmount: 18900,
    status: "Completada",
  },
];

export const monthlyBalances: MonthlyBalance[] = [
  { month: "Abr", income: 3800000, expense: 1950000 },
  { month: "May", income: 4100000, expense: 2050000 },
  { month: "Jun", income: 3950000, expense: 1880000 },
  { month: "Jul", income: 4450000, expense: 2200000 },
  { month: "Ago", income: 4600000, expense: 2100000 },
  { month: "Sep", income: 4820500, expense: 2140300 },
];

export const categoryBreakdown = [
  { name: "Mates", percentage: 45, color: "#9C5A2E" },
  { name: "Bombillas", percentage: 25, color: "#C87941" },
  { name: "Yerba", percentage: 20, color: "#3E8E5A" },
  { name: "Accesorios", percentage: 10, color: "#D98A2B" },
];

export const stockAlerts = [
  {
    id: "alt-1",
    name: "Mate Imperial Premium",
    sku: "MT-018",
    remaining: 3,
    level: "critical",
  },
  {
    id: "alt-2",
    name: "Bombilla Cincelada Especial",
    sku: "BB-0205",
    remaining: 4,
    level: "warning",
  },
  {
    id: "alt-3",
    name: "Canasta Matera Cuero Genuino",
    sku: "AC-0402",
    remaining: 6,
    level: "warning",
  },
  {
    id: "alt-4",
    name: "Termo Acero Inoxidable 1L",
    sku: "TM-0301",
    remaining: 0,
    level: "out-of-stock",
  },
];
