import { Product, Sale, MonthlyBalance, Client, StockMovement, Supplier } from "./types";

export const initialSuppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "Taller Artesanal Salta",
    contactName: "Don Ernesto Corvalán",
    phone: "+54 387 412-7893",
    email: "corvalan.artesanias@gmail.com",
    city: "Salta, Salta",
    category: "Mates y accesorios",
    notes: "Proveedor principal de mates calabaza. Entrega mensual. Acepta transferencia.",
  },
  {
    id: "sup-2",
    name: "Metalúrgica Lanús Artesanías",
    contactName: "Héctor Salvini",
    phone: "+54 11 4240-5561",
    email: "metalurgica.lanus@outlook.com",
    city: "Lanús, Buenos Aires",
    category: "Bombillas y virolas",
    notes: "Especialista en bombillas artesanales y virolas de alpaca. Pedido mínimo: 20 unidades.",
  },
  {
    id: "sup-3",
    name: "Molino Misionero Don Arnaldo",
    contactName: "Arnaldo Kessler",
    phone: "+54 376 442-0187",
    email: "molino.arnaldo@misionero.com",
    city: "Posadas, Misiones",
    category: "Yerba mate",
    notes: "Yerba orgánica elaborada en Misiones. Entregas quincenales. Producto premium.",
  },
  {
    id: "sup-4",
    name: "Importaciones Rioplatenses",
    contactName: "Marcela Duhalde",
    phone: "+54 11 4510-3322",
    email: "ventas@importrioplatense.com.ar",
    city: "CABA, Buenos Aires",
    category: "Accesorios importados",
    notes: "Accesorios y artículos importados de Brasil y Uruguay. Requiere adelanto del 50%.",
  },
  {
    id: "sup-5",
    name: "Marroquinería San Telmo",
    contactName: "Fabián Iriarte",
    phone: "+54 11 4362-9047",
    email: "santelmo.cueros@gmail.com",
    city: "San Telmo, CABA",
    category: "Cueros y terminaciones",
    notes: "Cuero vacuno seleccionado para terminaciones de mates. Trato directo con el curtidor.",
  },
  {
    id: "sup-6",
    name: "Distribuidora Lumilagro / Stanley",
    contactName: "Gustavo Mena",
    phone: "+54 800 777-9865",
    email: "distribuidora@lumilagro.com.ar",
    city: "Córdoba, Córdoba",
    category: "Termos y frascos",
    notes: "Distribuidor oficial de termos Stanley y Lumilagro para la región centro. Condiciones especiales.",
  },
];

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Mate Imperial Calabaza",
    subtitle: "Cuero repujado con virola de alpaca",
    sku: "MT-0142",
    category: "Mates",
    listPrice: 12500,
    price: 18900,
    stock: 42,
    status: "En stock",
    minStock: 10,
    supplier: "Taller Artesanal Salta",
    initialStockDate: "15/07/2026 09:30",
    lastRestockDate: "20/09/2026 14:15",
    hasVariants: true,
    variants: [
      { id: "var-1-1", name: "Negro Cincelado", sku: "MT-0142-NEG", stock: 24 },
      { id: "var-1-2", name: "Marrón Suela", sku: "MT-0142-MAR", stock: 18 },
    ],
  },
  {
    id: "prod-2",
    name: "Mate Torpedo Premium",
    subtitle: "Cuero vaqueta seleccionado",
    sku: "MT-0143",
    category: "Mates",
    listPrice: 11000,
    price: 16500,
    stock: 8,
    status: "Bajo stock",
    minStock: 10,
    supplier: "Taller Artesanal Salta",
    initialStockDate: "18/07/2026 11:00",
    lastRestockDate: "05/09/2026 16:40",
    hasVariants: true,
    variants: [
      { id: "var-2-1", name: "Negro Azabache", sku: "MT-0143-NEG", stock: 5 },
      { id: "var-2-2", name: "Marrón Habano", sku: "MT-0143-MAR", stock: 3 },
    ],
  },
  {
    id: "prod-3",
    name: "Mate Camionero Uruguayo",
    subtitle: "Boca ancha, virola cincelada lisa",
    sku: "MT-0144",
    category: "Mates",
    listPrice: 13000,
    price: 19800,
    stock: 24,
    status: "En stock",
    minStock: 12,
    supplier: "Importaciones Rioplatenses",
    initialStockDate: "20/07/2026 10:15",
    lastRestockDate: "15/09/2026 11:20",
    hasVariants: true,
    variants: [
      { id: "var-3-1", name: "Negro Mate", sku: "MT-0144-NEG", stock: 14 },
      { id: "var-3-2", name: "Cuero Crudo", sku: "MT-0144-CRU", stock: 10 },
    ],
  },
  {
    id: "prod-4",
    name: "Bombilla Pico de Loro Alpaca",
    subtitle: "Filtro cuchara resorte desmontable",
    sku: "BB-0201",
    category: "Bombillas",
    listPrice: 4800,
    price: 7200,
    stock: 65,
    status: "En stock",
    minStock: 15,
    supplier: "Metalúrgica Lanús Artesanías",
    initialStockDate: "12/07/2026 14:00",
    lastRestockDate: "22/09/2026 17:30",
  },
  {
    id: "prod-5",
    name: "Bombilla Cincelada Especial",
    subtitle: "Alpaca con detalles artesanales",
    sku: "BB-0205",
    category: "Bombillas",
    listPrice: 5800,
    price: 8900,
    stock: 4,
    status: "Bajo stock",
    minStock: 8,
    supplier: "Metalúrgica Lanús Artesanías",
    initialStockDate: "15/07/2026 15:45",
    lastRestockDate: "02/09/2026 12:10",
  },
  {
    id: "prod-6",
    name: "Set Mate Imperial + Kit",
    subtitle: "Incluye mate, bombilla y bolso matero",
    sku: "ST-0501",
    category: "Sets",
    listPrice: 23000,
    price: 34500,
    stock: 15,
    status: "En stock",
    minStock: 5,
    supplier: "Taller Artesanal Salta",
    initialStockDate: "25/07/2026 09:00",
    lastRestockDate: "18/09/2026 10:50",
  },
  {
    id: "prod-7",
    name: "Yerba Mate Artesanal Barbaquá 1kg",
    subtitle: "Estacionamiento natural 24 meses",
    sku: "YB-0010",
    category: "Yerba",
    listPrice: 3000,
    price: 4500,
    stock: 120,
    status: "En stock",
    minStock: 30,
    supplier: "Molino Misionero Don Arnaldo",
    initialStockDate: "01/08/2026 08:30",
    lastRestockDate: "24/09/2026 15:00",
  },
  {
    id: "prod-8",
    name: "Termo Acero Inoxidable 1L",
    subtitle: "Doble capa térmica con manija cuero",
    sku: "TM-0301",
    category: "Termos",
    listPrice: 19000,
    price: 28900,
    stock: 0,
    status: "Agotado",
    minStock: 6,
    supplier: "Distribuidora Lumilagro / Stanley",
    initialStockDate: "05/08/2026 10:00",
    lastRestockDate: "28/08/2026 14:00",
  },
  {
    id: "prod-9",
    name: "Canasta Matera Cuero Genuino",
    subtitle: "Divisiones acolchadas reforzadas",
    sku: "AC-0402",
    category: "Accesorios",
    listPrice: 15000,
    price: 22400,
    stock: 6,
    status: "Bajo stock",
    minStock: 8,
    supplier: "Marroquinería San Telmo",
    initialStockDate: "10/08/2026 11:30",
    lastRestockDate: "08/09/2026 13:20",
  },
];

export const initialStockMovements: StockMovement[] = [
  // ── Re-stocks recientes ──────────────────────────────────────────────────
  {
    id: "smov-1",
    productId: "prod-7",
    productName: "Yerba Mate Artesanal Barbaquá 1kg",
    sku: "YB-0010",
    category: "Yerba",
    type: "Re-stock",
    quantity: 50,
    previousStock: 70,
    newStock: 120,
    date: "24/09/2026 15:00",
    costPerUnit: 3000,
    totalCost: 150000,
    supplier: "Molino Misionero Don Arnaldo",
    notes: "Lote de cosecha estacionamiento 24 meses",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-2",
    productId: "prod-4",
    productName: "Bombilla Pico de Loro Alpaca",
    sku: "BB-0201",
    category: "Bombillas",
    type: "Re-stock",
    quantity: 30,
    previousStock: 35,
    newStock: 65,
    date: "22/09/2026 17:30",
    costPerUnit: 4800,
    totalCost: 144000,
    supplier: "Metalúrgica Lanús Artesanías",
    notes: "Reposición para feria del fin de semana",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-3",
    productId: "prod-1",
    productName: "Mate Imperial Calabaza",
    sku: "MT-0142",
    category: "Mates",
    type: "Re-stock",
    quantity: 20,
    previousStock: 22,
    newStock: 42,
    date: "20/09/2026 14:15",
    costPerUnit: 12500,
    totalCost: 250000,
    supplier: "Taller Artesanal Salta",
    notes: "Calabazas seleccionadas con virola labrada",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-4",
    productId: "prod-6",
    productName: "Set Mate Imperial + Kit",
    sku: "ST-0501",
    category: "Sets",
    type: "Re-stock",
    quantity: 10,
    previousStock: 5,
    newStock: 15,
    date: "18/09/2026 10:50",
    costPerUnit: 23000,
    totalCost: 230000,
    supplier: "Taller Artesanal Salta",
    notes: "Armado de sets completos para día de la madre",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-5",
    productId: "prod-3",
    productName: "Mate Camionero Uruguayo",
    sku: "MT-0144",
    category: "Mates",
    type: "Re-stock",
    quantity: 15,
    previousStock: 9,
    newStock: 24,
    date: "15/09/2026 11:20",
    costPerUnit: 13000,
    totalCost: 195000,
    supplier: "Importaciones Rioplatenses",
    notes: "Ingreso de virolas cinceladas lisas",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-6",
    productId: "prod-9",
    productName: "Canasta Matera Cuero Genuino",
    sku: "AC-0402",
    category: "Accesorios",
    type: "Re-stock",
    quantity: 5,
    previousStock: 1,
    newStock: 6,
    date: "08/09/2026 13:20",
    costPerUnit: 15000,
    totalCost: 75000,
    supplier: "Marroquinería San Telmo",
    notes: "Pedido especial de cuero vacuno marrón",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-7",
    productId: "prod-2",
    productName: "Mate Torpedo Premium",
    sku: "MT-0143",
    category: "Mates",
    type: "Re-stock",
    quantity: 10,
    previousStock: 0,
    newStock: 10,
    date: "05/09/2026 16:40",
    costPerUnit: 11000,
    totalCost: 110000,
    supplier: "Taller Artesanal Salta",
    notes: "Reabastecimiento de torpedo vaqueta",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-8",
    productId: "prod-5",
    productName: "Bombilla Cincelada Especial",
    sku: "BB-0205",
    category: "Bombillas",
    type: "Re-stock",
    quantity: 10,
    previousStock: 2,
    newStock: 12,
    date: "02/09/2026 12:10",
    costPerUnit: 5800,
    totalCost: 58000,
    supplier: "Metalúrgica Lanús Artesanías",
    notes: "Reingreso por alta demanda",
    registeredBy: "Leonel Paz",
  },
  // ── Ingresos iniciales (Alta de catálogo) ──────────────────────────────────
  {
    id: "smov-9",
    productId: "prod-8",
    productName: "Termo Acero Inoxidable 1L",
    sku: "TM-0301",
    category: "Termos",
    type: "Ingreso inicial",
    quantity: 15,
    previousStock: 0,
    newStock: 15,
    date: "05/08/2026 10:00",
    costPerUnit: 19000,
    totalCost: 285000,
    supplier: "Distribuidora Lumilagro / Stanley",
    notes: "Carga inicial de termos al inventario",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-10",
    productId: "prod-7",
    productName: "Yerba Mate Artesanal Barbaquá 1kg",
    sku: "YB-0010",
    category: "Yerba",
    type: "Ingreso inicial",
    quantity: 100,
    previousStock: 0,
    newStock: 100,
    date: "01/08/2026 08:30",
    costPerUnit: 3000,
    totalCost: 300000,
    supplier: "Molino Misionero Don Arnaldo",
    notes: "Primer lote de yerba artesanal",
    registeredBy: "Leonel Paz",
  },
  {
    id: "smov-11",
    productId: "prod-1",
    productName: "Mate Imperial Calabaza",
    sku: "MT-0142",
    category: "Mates",
    type: "Ingreso inicial",
    quantity: 30,
    previousStock: 0,
    newStock: 30,
    date: "15/07/2026 09:30",
    costPerUnit: 12500,
    totalCost: 375000,
    supplier: "Taller Artesanal Salta",
    notes: "Apertura de catálogo - Mate Imperial",
    registeredBy: "Leonel Paz",
  },
];

export const initialClients: Client[] = [
  {
    id: "cli-1",
    name: "Lucía Fernández",
    initials: "LF",
    phone: "+54 9 11 4500-1000",
    email: "lucia.fernandez@gmail.com",
    dni: "38.291.482",
  },
  {
    id: "cli-2",
    name: "Mateo Gómez",
    initials: "MG",
    phone: "+54 9 11 4537-1082",
    email: "mateo.gomez@gmail.com",
    dni: "41.982.113",
  },
  {
    id: "cli-3",
    name: "Diego Torres",
    initials: "DT",
    phone: "+54 9 11 4574-1164",
    email: "diego.torres@gmail.com",
    dni: "35.109.842",
  },
  {
    id: "cli-4",
    name: "Camila Rodríguez",
    initials: "CR",
    phone: "+54 9 11 4611-1246",
    email: "camila.rodriguez@gmail.com",
    dni: "42.741.005",
  },
  {
    id: "cli-5",
    name: "Juan Pablo Rossi",
    initials: "JR",
    phone: "+54 9 11 4648-1328",
    email: "juan.rossi@gmail.com",
    dni: "33.820.491",
  },
];

export const initialSales: Sale[] = [
  // ── Lucía Fernández: todo al día ─────────────────────────────────────────
  {
    id: "sale-1",
    clientId: "cli-1",
    clientName: "Lucía Fernández",
    clientInitials: "LF",
    clientPhone: "+54 9 11 4500-1000",
    clientEmail: "lucia.fernandez@gmail.com",
    clientDni: "38.291.482",
    productName: "Set Mate Imperial + Kit",
    date: "19 Sep",
    method: "Efectivo",
    amount: 34500,
    paidAmount: 34500,
    status: "Completada",
  },
  {
    id: "sale-6",
    clientId: "cli-1",
    clientName: "Lucía Fernández",
    clientInitials: "LF",
    clientPhone: "+54 9 11 4500-1000",
    clientEmail: "lucia.fernandez@gmail.com",
    clientDni: "38.291.482",
    productName: "Bombilla Cincelada Especial",
    date: "10 Sep",
    method: "Transferencia",
    amount: 8900,
    paidAmount: 8900,
    status: "Completada",
  },

  // ── Mateo Gómez: DEUDA TOTAL — nunca pagó ────────────────────────────────
  {
    id: "sale-2",
    clientId: "cli-2",
    clientName: "Mateo Gómez",
    clientInitials: "MG",
    clientPhone: "+54 9 11 4537-1082",
    clientEmail: "mateo.gomez@gmail.com",
    clientDni: "41.982.113",
    productName: "Mate Imperial Calabaza",
    date: "19 Sep",
    method: "Fiado",
    amount: 18900,
    paidAmount: 0,
    status: "Pendiente",
  },
  {
    id: "sale-7",
    clientId: "cli-2",
    clientName: "Mateo Gómez",
    clientInitials: "MG",
    clientPhone: "+54 9 11 4537-1082",
    clientEmail: "mateo.gomez@gmail.com",
    clientDni: "41.982.113",
    productName: "Yerba Barbaquá 1kg x2",
    date: "15 Sep",
    method: "Fiado",
    amount: 9000,
    paidAmount: 0,
    status: "Pendiente",
  },

  // ── Diego Torres: al día ──────────────────────────────────────────────────
  {
    id: "sale-3",
    clientId: "cli-3",
    clientName: "Diego Torres",
    clientInitials: "DT",
    clientPhone: "+54 9 11 4574-1164",
    clientEmail: "diego.torres@gmail.com",
    clientDni: "35.109.842",
    productName: "Mate Torpedo + Kit",
    date: "18 Sep",
    method: "Transferencia",
    amount: 22300,
    paidAmount: 22300,
    status: "Completada",
  },

  // ── Camila Rodríguez: DEUDA PARCIAL — pagó $10.000, debe $38.700 ─────────
  {
    id: "sale-4",
    clientId: "cli-4",
    clientName: "Camila Rodríguez",
    clientInitials: "CR",
    clientPhone: "+54 9 11 4611-1246",
    clientEmail: "camila.rodriguez@gmail.com",
    clientDni: "42.741.005",
    productName: "Termo Acero 1L + Mate Camionero",
    date: "18 Sep",
    method: "Efectivo parcial",
    amount: 48700,
    paidAmount: 10000,
    status: "Pendiente",
  },
  {
    id: "sale-8",
    clientId: "cli-4",
    clientName: "Camila Rodríguez",
    clientInitials: "CR",
    clientPhone: "+54 9 11 4611-1246",
    clientEmail: "camila.rodriguez@gmail.com",
    clientDni: "42.741.005",
    productName: "Bombilla Pico de Loro Alpaca",
    date: "5 Sep",
    method: "Mercado Pago",
    amount: 7200,
    paidAmount: 7200,
    status: "Completada",
  },

  // ── Juan Pablo Rossi: MÚLTIPLES DEUDAS ($35.900 pendientes) ──────────────
  {
    id: "sale-5",
    clientId: "cli-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    clientPhone: "+54 9 11 4648-1328",
    clientEmail: "juan.rossi@gmail.com",
    clientDni: "33.820.491",
    productName: "Canasta Matera Cuero Genuino",
    date: "17 Sep",
    method: "Fiado",
    amount: 22400,
    paidAmount: 0,
    status: "Pendiente",
  },
  {
    id: "sale-9",
    clientId: "cli-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    clientPhone: "+54 9 11 4648-1328",
    clientEmail: "juan.rossi@gmail.com",
    clientDni: "33.820.491",
    productName: "Yerba Barbaquá 1kg x3",
    date: "10 Sep",
    method: "Fiado",
    amount: 13500,
    paidAmount: 0,
    status: "Pendiente",
  },
  {
    id: "sale-10",
    clientId: "cli-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    clientPhone: "+54 9 11 4648-1328",
    clientEmail: "juan.rossi@gmail.com",
    clientDni: "33.820.491",
    productName: "Mate Imperial Calabaza",
    date: "2 Sep",
    method: "Transferencia",
    amount: 18900,
    paidAmount: 18900,
    status: "Completada",
  },
];

export const monthlyBalances: MonthlyBalance[] = [
  { month: "Abr", income: 3800000, expense: 1950000 },
  { month: "May", income: 4100000, expense: 2050000 },
  { month: "Jun", income: 3950000, expense: 1880000 },
  { month: "Jul", income: 4450000, expense: 2200000 },
  { month: "Ago", income: 4600000, expense: 2100000 },
  { month: "Sep", income: 4820500, expense: 2140300 },
];

export const categoryBreakdown = [
  { name: "Mates", percentage: 45, color: "#9C5A2E" },
  { name: "Bombillas", percentage: 25, color: "#C87941" },
  { name: "Yerba", percentage: 20, color: "#3E8E5A" },
  { name: "Accesorios", percentage: 10, color: "#D98A2B" },
];

export const stockAlerts = [
  {
    id: "alt-1",
    name: "Mate Imperial Premium",
    sku: "MT-018",
    remaining: 3,
    level: "critical",
  },
  {
    id: "alt-2",
    name: "Bombilla Cincelada Especial",
    sku: "BB-0205",
    remaining: 4,
    level: "warning",
  },
  {
    id: "alt-3",
    name: "Canasta Matera Cuero Genuino",
    sku: "AC-0402",
    remaining: 6,
    level: "warning",
  },
  {
    id: "alt-4",
    name: "Termo Acero Inoxidable 1L",
    sku: "TM-0301",
    remaining: 0,
    level: "out-of-stock",
  },
];
