import { Product, Sale, Expense, MonthlyBalance } from "./types";

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Mate Imperial Calabaza",
    subtitle: "Cuero repujado con virola de alpaca",
    sku: "MT-0142",
    category: "Mates",
    price: 18900,
    stock: 42,
    status: "En stock",
  },
  {
    id: "prod-2",
    name: "Mate Torpedo Premium",
    subtitle: "Cuero vaqueta seleccionado marrón",
    sku: "MT-0143",
    category: "Mates",
    price: 16500,
    stock: 8,
    status: "Bajo stock",
  },
  {
    id: "prod-3",
    name: "Mate Camionero Uruguayo",
    subtitle: "Boca ancha, virola cincelada lisa",
    sku: "MT-0144",
    category: "Mates",
    price: 19800,
    stock: 24,
    status: "En stock",
  },
  {
    id: "prod-4",
    name: "Bombilla Pico de Loro Alpaca",
    subtitle: "Filtro cuchara resorte desmontable",
    sku: "BB-0201",
    category: "Bombillas",
    price: 7200,
    stock: 65,
    status: "En stock",
  },
  {
    id: "prod-5",
    name: "Bombilla Cincelada Especial",
    subtitle: "Alpaca con detalles artesanales",
    sku: "BB-0205",
    category: "Bombillas",
    price: 8900,
    stock: 4,
    status: "Bajo stock",
  },
  {
    id: "prod-6",
    name: "Set Mate Imperial + Kit",
    subtitle: "Incluye mate, bombilla y bolso matero",
    sku: "ST-0501",
    category: "Sets",
    price: 34500,
    stock: 15,
    status: "En stock",
  },
  {
    id: "prod-7",
    name: "Yerba Mate Artesanal Barbaquá 1kg",
    subtitle: "Estacionamiento natural 24 meses",
    sku: "YB-0010",
    category: "Yerba",
    price: 4500,
    stock: 120,
    status: "En stock",
  },
  {
    id: "prod-8",
    name: "Termo Acero Inoxidable 1L",
    subtitle: "Doble capa térmica con manija cuero",
    sku: "TM-0301",
    category: "Termos",
    price: 28900,
    stock: 0,
    status: "Agotado",
  },
  {
    id: "prod-9",
    name: "Canasta Matera Cuero Genuino",
    subtitle: "Divisiones acolchadas reforzadas",
    sku: "AC-0402",
    category: "Accesorios",
    price: 22400,
    stock: 6,
    status: "Bajo stock",
  },
];

export const initialSales: Sale[] = [
  {
    id: "sale-1",
    clientName: "Lucía Fernández",
    clientInitials: "LF",
    productName: "Set Mate Imperial",
    date: "19 Sep",
    method: "Efectivo",
    amount: 18500,
    status: "Completada",
  },
  {
    id: "sale-2",
    clientName: "Mateo Gómez",
    clientInitials: "MG",
    productName: "Bombilla Alpaca Pico Loro",
    date: "19 Sep",
    method: "Mercado Pago",
    amount: 7200,
    status: "Pendiente",
  },
  {
    id: "sale-3",
    clientName: "Diego Torres",
    clientInitials: "DT",
    productName: "Mate Torpedo + Kit",
    date: "18 Sep",
    method: "Transferencia",
    amount: 22300,
    status: "Completada",
  },
  {
    id: "sale-4",
    clientName: "Camila Rodríguez",
    clientInitials: "CR",
    productName: "Mate Camionero Cuero",
    date: "18 Sep",
    method: "Tarjeta de débito",
    amount: 19800,
    status: "Completada",
  },
  {
    id: "sale-5",
    clientName: "Juan Pablo Rossi",
    clientInitials: "JR",
    productName: "Yerba Barbaquá x 3kg",
    date: "17 Sep",
    method: "Transferencia",
    amount: 13500,
    status: "Completada",
  },
];

export const monthlyBalances: MonthlyBalance[] = [
  { month: "Abr", income: 3800000, expense: 1950000 },
  { month: "May", income: 4100000, expense: 2050000 },
  { month: "Jun", income: 3950000, expense: 1880000 },
  { month: "Jul", income: 4450000, expense: 2200000 },
  { month: "Ago", income: 4600000, expense: 2100000 },
  { month: "Sep", income: 4820500, expense: 2140300 },
];

export const categoryBreakdown = [
  { name: "Mates", percentage: 45, color: "#9C5A2E" },
  { name: "Bombillas", percentage: 25, color: "#C87941" },
  { name: "Yerba", percentage: 20, color: "#3E8E5A" },
  { name: "Accesorios", percentage: 10, color: "#D98A2B" },
];

export const stockAlerts = [
  {
    id: "alt-1",
    name: "Mate Imperial Premium",
    sku: "MT-018",
    remaining: 3,
    level: "critical",
  },
  {
    id: "alt-2",
    name: "Bombilla Cincelada Especial",
    sku: "BB-0205",
    remaining: 4,
    level: "warning",
  },
  {
    id: "alt-3",
    name: "Canasta Matera Cuero Genuino",
    sku: "AC-0402",
    remaining: 6,
    level: "warning",
  },
  {
    id: "alt-4",
    name: "Termo Acero Inoxidable 1L",
    sku: "TM-0301",
    remaining: 0,
    level: "out-of-stock",
  },
];
